# Window Properties
WIDTH = 360
HEIGHT = 240
MID_WIDTH = WIDTH//2
MID_HEIGHT = HEIGHT//2

# Others
FPS = 60
SCORE_OFFSET = 10

# Ball Properties
BALL_RADIUS = 3
BALL_SPEED = 5
BALL_COLOR = 7  # White

# Paddle Properties
PADDLE_WIDTH = 4
PADDLE_HEIGHT = 40
PADDLE_SPEED = 4
PADDLE_COLOR = 7
PADDLE_OFFSET = 5
PADDLE_SECTIONS = 5
SECTION_HEIGHT = PADDLE_HEIGHT // PADDLE_SECTIONS
